### PR TITLE
Syntax fails removed+ Beautified

### PR DESCRIPTION
**Pull request by maxibanki**
What do you think about that?

### CODE REVIEW

**Comment by xDefcon** [comment]
Will beautify on next version, ty!

**Comment by maxibanki** [comment]
Why do you not apply that? :/

**Comment by xDefcon** [comment]
I don't like 2 spaces indentation style.

**Comment by JonasBoegle** [comment]
just merge it and change stuff afterwards

**Comment by maxibanki** [comment]
You are strange.... that is the default way of making code clear

**Comment by xDefcon** [comment]
It is the common code style for JavaScript, but i prefer use 4 spaces instead of 2.

**Comment by maxibanki** [comment]
kk but remember, most of the if clauses in your script are not valid for ECMAScript.

**Comment by xDefcon** [comment]
@maxibanki are you talking about spaces between "if" and condition?

**Pull request closed without merging**
