### PR TITLE
fixed clacks issue

### PR DESCRIPTION
**Pull request by GandalfGuenter**
now the nick gets updated even if no change is detected

### CODE REVIEW

**Comment by xDefcon** [comment]
This will be a good idea, but sinusbot.setNick() just set nick in the web interface...
Example: 
TS3 Real nick: BOT1111
WebInterface nick: BOT

sinusbot.setNick("BOT") does anything, because it is the same of the webinterface config.

To fix this problem there are 2 solutions:
a) get real ts3 nick by iterating on ts3-channels
b) every X sec, set a different nick, and immediatly change with the default one, (setNick("BOT.") then setNick("BOT"))

**Comment by GandalfGuenter** [comment]
did you try it? it worked for me ^^

**Comment by xDefcon** [comment]
I can re-test but this needs some time, because to replicate this situation i have to wait to a bot crash

**Comment by GandalfGuenter** [comment]
you could also disconnect the bot, join with a client named "test" and rename the bot to "test".
If you connect the bot again the bot is called "test1" and if you disconnect the client "test" the bot renames itself to "test".

**Comment by xDefcon** [comment]
Yes, it did the same.

sinusbot.setNick() really sets a nick via TS3.
sinusbot.getNick() gets the nick by webinterface, and not the real one on TS3.

Thanks for suggesting me that!

**Pull request merged**
